apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: springboot-app
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 600
      serviceAccountName: SA_NAME
      containers:
      - image: gcr.io/GCP_PROJECT/spring-boot-app
        ports:
        - containerPort: 8085
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
  traffic:
  - percent: 100
    latestRevision: true