name: Spring Boot Deployment

on:
  push:
    branches:
      - integration
  workflow_dispatch:

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  SA_NAME: SB-React-WebApp

jobs:
  setup:
    name: Utility Setup
    runs-on: ubuntu-latest

    steps:
    #Checkout the repository code
    - name: Checkout
      uses: actions/checkout@v2
    
    #Set the java-version to use
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    # Setup gcloud CLI
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker & Install Beta
      run: |-
        gcloud auth configure-docker --quiet
        gcloud components install beta

  build-deploy:
    name: Build and Deploy
    needs: setup
    runs-on: ubuntu-latest

    steps:
    #Checkout the repository code
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Publish to GCR 
      run: |-
        cd visitcount
        ./mvnw compile com.google.cloud.tools:jib-maven-plugin:2.8.0:build -Dimage=gcr.io/$GCP_PROJECT/spring-boot-app

    - name: Deploy to Cloud Run
      run: |-
        cd visitcount
        sed -i "s/SA_NAME/$SA_NAME/g" spring-boot-run.yaml
        sed -i "s/GCP_PROJECT/$GCP_PROJECT/g" spring-boot-run.yaml
        gcloud beta run services replace spring-boot-run.yaml  --platform=managed --region=europe-west1
        gcloud run services add-iam-policy-binding spring-boot-app --platform=managed --region=europe-west1 --member="allUsers" --role="roles/run.invoker"
