name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - integration
  workflow_dispatch:


jobs:
  setup-build-publish-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    #Checkout the repository code
    - name: Checkout
      uses: actions/checkout@v2

    
    #Cache the maven dependencies to .m2 directory
    # - name: Cache local Maven repository
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.m2/repository/visitcount
    #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    #     restore-keys: |
    #       ${{ runner.os }}-maven-
    
    #Set the java-version to use
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Maven Clean
      run: |-
        ./mvnw clean install
    
    
    # Build the jar file with maven
    - name: Build with Maven
      run: |-
        cd visitcount
        ./mvnw -DskipTests package