name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - integration
  workflow_dispatch:

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  setup-build-publish-deploy:
    name: Build and Deploy
    runs-on: ubuntu-20.04

    steps:
    #Checkout the repository code
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    # Cache the maven dependencies to .m2 directory
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/visitcount
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    #Set the java-version to use
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    # - name: Maven Clean
    #   run: |-
    #     cd visitcount
    #     ./mvnw clean
    
    # Build the jar file with maven
    - name: Build with Maven
      run: |-
        cd visitcount
        ./mvnw -DskipTests package

    # Setup gcloud CLI
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Deploy to GCR 
      run: |-
        cd visitcount
        ./mvnw compile com.google.cloud.tools:jib-maven-plugin:2.8.0:build -Dimage=gcr.io/$GCP_PROJECT/spring-react-app

    - name: Deploy to Cloud Run
      run: |-
        gcloud components install beta
        gcloud beta run services replace cloud-run.yaml  --platform=managed --region=europe-west1
        gcloud run services add-iam-policy-binding spring-react-app --platform=managed --region=europe-west1 --member="allUsers" --role="roles/run.invoker"