name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - integration
  workflow_dispatch:


jobs:
  setup-build-publish-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    #Checkout the repository code
    - name: Checkout
      uses: actions/checkout@v2
    
    #Cache the maven dependencies to .m2 directory
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository/visitcount
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    #Set the java-version to use
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    
    # Build the jar file with maven
    - name: Build with Maven
      run: |-
        cd visitcount
        ./mvnw -B package --file pom.xml -Dmaven.test.skip=true
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
     
    - name: Node Build
      run: |- 
        cd ui
        npm install
        npm run build
    
    - name: Copy Build
      run: |- 
        pwd
        cp /ui/build/. /visitcount/target/classes/public/
        cd visitcount/target/classes/public
        ls