name: React App Deployment

on:
  workflow_run:
    workflows: ["Spring Boot Deployment"]
    branches: [integration]
    types: 
      - completed
  workflow_dispatch:

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  SA_NAME: SB-React-WebApp

jobs:
  setup:
    name: Utility Setup
    runs-on: ubuntu-latest

    steps:
    #Checkout the repository code
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Setup gcloud CLI
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
    
    - name: Configure Docker & Install Beta
      run: |-
        gcloud auth configure-docker --quiet
        gcloud components install beta

  build-deploy:
    name: Build and Deploy
    needs: setup
    runs-on: ubuntu-latest

    steps:
    #Checkout the repository code
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |-
        cd ui/
        BACK_URL=$(gcloud run services describe spring-boot-app --platform managed --region europe-west1 --format 'value(status.url)')
        docker build --build-arg URL=$BACK_URL -t gcr.io/$GCP_PROJECT/react-app .
          
    - name: Push Docker image
      run: docker push gcr.io/$GCP_PROJECT/react-app

    - name: Deploy React App
      run: |-
        cd ui
        sed -i "s/SA_NAME/$SA_NAME/g" react-run.yaml
        sed -i "s/GCP_PROJECT/$GCP_PROJECT/g" react-run.yaml
        gcloud beta run services replace react-run.yaml  --platform=managed --region=europe-west1
        gcloud run services add-iam-policy-binding react-app --platform=managed --region=europe-west1 --member="allUsers" --role="roles/run.invoker"
